# PART 0 : GENERAL CONFIGURATION
## RUN/EXP NAME:
run_name: "EXP NAME"

## WORKING DIRECTORY:
working_directory: "/path/to/working/directory" # path where the output files will be saved

## RAW DATA:
path_to_raw_data: "/path/to/raw/data" # path to the directory containing the fastq files

## DESIGN MATRIX:
design_matrix: "/path/to/design/matrix" # path to the design matrix file

## Number of Cores:
nbCores_bowtie2: 12
nbCores_picard: 12
nbCores_samtools: 10
nbCores_deepTools: 12
nbCores_macs2: 12
nbCores_trim_galore: 4 
#NB: 4 cores is the maximum recommended (and defaults to 4 if more is chosen), 4 cores would be: 4 (read) + 4 (write) + 4 (Cutadapt) + 2 (extra Cutadapt) + 1 (Trim Galore) = 15

## Max available Memory and Cores:
available_memory: 8 # in GB
available_cores: 8

## Delete Tmp Files:
delete_tmp_files: false

## ATAC-seq mode:
atac_seq: false


###################### PART 1 : QUALITY_CONTROL ######################
## FastQC:
fastqc_args: "" # additional arguments to pass to FastQC, example: "--threads 10 --nogroup"


###################### PART 2 : ALIGNEMENT -> REGULAR_SORTED_MAPPED ######################
## Trimming and adapter removal:
trim_data: False
adapter: "" # can be empty string "" for auto detection of adapter-sequence or one of ["illumina", "stranded_illumina", "nextera", "small_rna"]

## ALignement with Bowtie2:
genome: "mm10" # mm10 or hg38
path_to_bowtie2_genome_idx: "" # required if index_genome is false
# Example : if index is /path/to/index/mm10/mm10.rev.2.bt2, then, path_to_bowtie2_genome_idx =  /path/to/index/mm10
# NB: Index prefix should be mm10 or hg38, example: mm10.rev.2.bt2
index_genome: false # if true, the genome will be indexed
path_to_genome_fasta: "" # required if index_genome is true

## Removing Duplicates: 
remove_duplicates: true # if true, duplicates will be removed
output_finale_file_with_duplicates: true # if true, the output folder will also contain BAM files with duplicates, only taken into account if remove_duplicates is true

## MAPQ to use for filtering, can be one value or a list of values
MAPQ: [0, 2] 

## Keep only regular reads (chr1, chr2, ..., chrX, chrY):
keep_only_regular_reads: true # if true, only reads mapped to regular chromosomes will be kept


###################### PART 3 : DOWNSAMPLING - TO_BIGWIG - PEAK_CALLING - HEATMAP_PROFILE_PLOT ######################
## Downsampling:
downsample: true
downsample_type: "ALL" #"ALL" or "Group", if "Group", "downsample_column" and "downsample_by_group" are required
downsample_column: "Factor" # The column where the groups are defined, required if downsampling by Group
downsample_specific_group: "" # If you want to downsample a specific group, empty string otherwise

## Converting to BigWig:
convert_to_BigWig: false # if true, the BAM files will be converted to BigWig files

## Peak Calling:
peak_calling: false # if true, peaks will be called
macs2_parameters: "--nomodel --extsize 147 --shift -73" # parameters to pass to MACS2
# Examples:
# CUT&Tag : "-f BAMPE -B --max-gap 2000 --min-length 200 -B --broad --broad-cutoff 0.1"
# ATAC-seq : "--nomodel --shift -100 --extsize 200 --broad"

## Differential Binding Analysis: (R - DiffBind)
diffbind: true
diffbind_pvalue: 0.05 # p-value threshold for differential binding analysis
diffbind_flip: true
user_peaks: "" #path to the peaks file if peak_calling is false or to use different peaks than the one generated by MACS2, empty string otherwise, required if diffBind is true and peak_calling is false
user_peak_caller: "" #required if peak file is provided, empty string otherwise, required if diffBind is true and peak_calling is false
path_to_regions: ""  #path to the regions file for the annotation of the peaks, empty string to skip the annotation of the peaks
overlaps_parameters: "-f 0.90" #i.e. -f 0.XX and/or -F 0.XX where XX is the percentage of overlap required to consider two regions as overlapping 


## Computing matrix -> Heatmap and Profile Plot
compute_matrix: false
compute_matrix_type: "reference-point" # scale-regions or reference-point
upstream: 3000 # Upstream distance from the reference
downstream: 3000 # Downstream distance from the reference
compute_matrix_parameters: "--referencePoint TSS --skipZeros"
specific_regions: "" # if specific regions (Example: L1Md) from the annotated peaks are to be used, empty string otherwise
plot_heatmap: false
plot_heatmap_parameters: "--colorMap RdBu"
plot_profile: false
plot_profile_parameters: ""
custom_regions: "" # if custom regions are to be used, empty string otherwise